// vue/src/components/app-header.vue
<script setup lang="ts">
import AppLogo from '@/components/app-logo.vue';
import AppLogoIcon from '@/components/app-logo-icon.vue';
import Breadcrumbs from '@/components/breadcrumbs.vue';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { NavigationMenu, NavigationMenuItem, NavigationMenuList, navigationMenuTriggerStyle } from '@/components/ui/navigation-menu';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import UserMenuContent from '@/components/user-menu-content.vue';
import { getInitials } from '@/composables/use-initials';
import type { BreadcrumbItem, NavItem, SharedData } from '@/types';
import { Link, usePage } from '@inertiajs/vue3';
import { BookOpen, Folder, LayoutGrid, Menu, Search, ChevronsUpDownIcon } from 'lucide-vue-next';
import { computed } from 'vue';
import ProjectSwitch from '@/components/project-switch.vue';

interface Props {
  breadcrumbs?: BreadcrumbItem[];
}

const props = withDefaults(defineProps<Props>(), {
  breadcrumbs: () => [],
});

const page = usePage<SharedData>();
const auth = computed(() => page.props.auth);

const isCurrentRoute = computed(() => (url: string) => page.url === url);

const activeItemStyles = computed(
  () => (url: string) => (isCurrentRoute.value(url) ? 'text-neutral-900 dark:bg-neutral-800 dark:text-neutral-100' : ''),
);

const mainNavItems: NavItem[] = [
  {
    title: 'Dashboard',
    href: '/dashboard',
    icon: LayoutGrid,
  },
];

const rightNavItems: NavItem[] = [
  {
    title: 'Repository',
    href: 'https://github.com/laravel/vue-starter-kit',
    icon: Folder,
  },
  {
    title: 'Documentation',
    href: 'https://laravel.com/docs/starter-kits#vue',
    icon: BookOpen,
  },
];
</script>

<template>
  <div>
    <div class="border-sidebar-border/80 border-b">
      <div class="mx-auto flex h-16 items-center px-4 md:max-w-7xl">
        <!-- Mobile Menu -->
        <div class="lg:hidden">
          <Sheet>
            <SheetTrigger :as-child="true">
              <Button variant="ghost" size="icon" class="mr-2 h-9 w-9">
                <Menu class="h-5 w-5" />
              </Button>
            </SheetTrigger>
            <SheetContent side="left" class="w-[300px] p-0">
              <SheetTitle class="sr-only">Navigation Menu</SheetTitle>
              <SheetHeader class="flex justify-start text-left">
                <AppLogoIcon class="size-6 fill-current text-black dark:text-white" />
              </SheetHeader>
              <div class="flex h-full flex-1 flex-col justify-between space-y-4 p-6">
                <nav class="-mx-3 space-y-2">
                  <!--<php-saas:projects>-->
                  <ProjectSwitch>
                    <Button variant="outline" class="flex w-full items-center justify-between px-1.5!">
                      <div class="flex items-center justify-center gap-2">
                        <Avatar class="size-6 rounded-md">
                          <AvatarFallback class="rounded-xs">
                            {{ getInitials(page.props.project_provider.current?.name.replaceAll(' ', '') ?? 'Select project') }}
                          </AvatarFallback>
                        </Avatar>
                        <span>{{ page.props.project_provider.current?.name || 'Select project' }}</span>
                      </div>
                      <ChevronsUpDownIcon class="size-4" />
                    </Button>
                  </ProjectSwitch>
                  <!--</php-saas:projects>-->
                  <Link
                    v-for="item in mainNavItems"
                    :key="item.title"
                    :href="item.href"
                    class="hover:bg-accent flex items-center gap-x-3 rounded-lg px-3 py-2 text-sm font-medium"
                    :class="activeItemStyles(item.href)"
                  >
                    <component v-if="item.icon" :is="item.icon" class="h-5 w-5" />
                    {{ item.title }}
                  </Link>
                </nav>
                <div class="flex flex-col space-y-4">
                  <a
                    v-for="item in rightNavItems"
                    :key="item.title"
                    :href="item.href"
                    target="_blank"
                    rel="noopener noreferrer"
                    class="flex items-center space-x-2 text-sm font-medium"
                  >
                    <component v-if="item.icon" :is="item.icon" class="h-5 w-5" />
                    <span>{{ item.title }}</span>
                  </a>
                </div>
              </div>
            </SheetContent>
          </Sheet>
        </div>

        <Link :href="route('dashboard')" class="flex items-center gap-x-2">
          <AppLogo />
        </Link>

        <!-- Desktop Menu -->
        <div class="hidden h-full lg:flex lg:flex-1">
          <NavigationMenu class="ml-6 flex h-full items-stretch">
            <NavigationMenuList class="flex h-full items-stretch space-x-1">
              <!--<php-saas:projects>-->
              <ProjectSwitch>
                <NavigationMenuItem asChild>
                  <Button variant="outline" class="px-1.5!">
                    <div class="flex items-center justify-center gap-2">
                      <Avatar v-if="page.props.project_provider.current" class="size-6 rounded-md">
                        <AvatarFallback class="rounded-xs">
                          {{ getInitials(page.props.project_provider.current.name.replaceAll(' ', '') ?? 'Select Project') }}
                        </AvatarFallback>
                      </Avatar>
                      <span>{{ page.props.project_provider.current?.name || 'Select project' }}</span>
                    </div>
                    <ChevronsUpDownIcon class="size-4" />
                  </Button>
                </NavigationMenuItem>
              </ProjectSwitch>
              <!--</php-saas:projects>-->
              <NavigationMenuItem v-for="(item, index) in mainNavItems" :key="index" class="relative flex h-full items-center">
                <Link :class="[navigationMenuTriggerStyle(), activeItemStyles(item.href), 'h-9 cursor-pointer px-3']" :href="item.href">
                  <component v-if="item.icon" :is="item.icon" class="mr-2 h-4 w-4" />
                  {{ item.title }}
                </Link>
                <div v-if="isCurrentRoute(item.href)" class="absolute bottom-0 left-0 h-0.5 w-full translate-y-px bg-black dark:bg-white"></div>
              </NavigationMenuItem>
            </NavigationMenuList>
          </NavigationMenu>
        </div>

        <div class="ml-auto flex items-center space-x-2">
          <div class="relative flex items-center space-x-1">
            <Button variant="ghost" size="icon" class="group h-9 w-9 cursor-pointer">
              <Search class="size-5 opacity-80 group-hover:opacity-100" />
            </Button>

            <div class="hidden space-x-1 lg:flex">
              <template v-for="item in rightNavItems" :key="item.title">
                <TooltipProvider :delay-duration="0">
                  <Tooltip>
                    <TooltipTrigger as-child>
                      <Button variant="ghost" size="icon" as-child class="group h-9 w-9 cursor-pointer">
                        <a :href="item.href" target="_blank" rel="noopener noreferrer">
                          <span class="sr-only">{{ item.title }}</span>
                          <component :is="item.icon" class="size-5 opacity-80 group-hover:opacity-100" />
                        </a>
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>{{ item.title }}</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </template>
            </div>
          </div>

          <DropdownMenu>
            <DropdownMenuTrigger :as-child="true">
              <Button variant="ghost" size="icon" class="focus-within:ring-primary relative size-10 w-auto rounded-lg p-1 focus-within:ring-2">
                <Avatar class="size-8 overflow-hidden rounded-lg">
                  <AvatarImage v-if="auth.user.avatar" :src="auth.user.avatar" :alt="auth.user.name" />
                  <AvatarFallback class="rounded-lg bg-neutral-200 font-semibold text-black dark:bg-neutral-700 dark:text-white">
                    {{ getInitials(auth.user?.name) }}
                  </AvatarFallback>
                </Avatar>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" class="w-56">
              <UserMenuContent :user="auth.user" />
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
    </div>

    <div v-if="props.breadcrumbs.length > 1" class="border-sidebar-border/70 flex w-full border-b">
      <div class="mx-auto flex h-12 w-full items-center justify-start px-4 text-neutral-500 md:max-w-7xl">
        <Breadcrumbs :breadcrumbs="breadcrumbs" />
      </div>
    </div>
  </div>
</template>

// resources/js-react/components/app-header.tsx
import { Breadcrumbs } from '@/components/breadcrumbs';
import { Icon } from '@/components/icon';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { NavigationMenu, NavigationMenuItem, NavigationMenuList, navigationMenuTriggerStyle } from '@/components/ui/navigation-menu';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { UserMenuContent } from '@/components/user-menu-content';
import { useInitials } from '@/hooks/use-initials';
import { cn } from '@/lib/utils';
import { type BreadcrumbItem, type NavItem, type SharedData } from '@/types';
import { Link, usePage } from '@inertiajs/react';
import { BookOpen, ChevronsUpDownIcon, Folder, LayoutGrid, Menu } from 'lucide-react';
import AppLogo from './app-logo';
import AppLogoIcon from './app-logo-icon';
import { ProjectSwitch } from '@/components/project-switch';
import Refresh from '@/components/refresh';

const mainNavItems: NavItem[] = [
  {
    title: 'Dashboard',
    href: route('dashboard'),
    icon: LayoutGrid,
  },
];

const rightNavItems: NavItem[] = [
  {
    title: 'Repository',
    href: 'https://github.com/laravel/react-starter-kit',
    icon: Folder,
  },
  {
    title: 'Documentation',
    href: 'https://laravel.com/docs/starter-kits#react',
    icon: BookOpen,
  },
];

const activeItemStyles = 'text-neutral-900 dark:bg-neutral-800 dark:text-neutral-100';

interface AppHeaderProps {
  breadcrumbs?: BreadcrumbItem[];
}

export function AppHeader({ breadcrumbs = [] }: AppHeaderProps) {
  const page = usePage<SharedData>();
  const { auth } = page.props;
  const getInitials = useInitials();
  return (
    <>
      <div className="border-sidebar-border/80 border-b">
        <div className="mx-auto flex h-16 items-center px-4 md:max-w-7xl">
          {/* Mobile Menu */}
          <div className="lg:hidden">
            <Sheet>
              <SheetTrigger asChild>
                <Button variant="ghost" size="icon" className="mr-2 h-[34px] w-[34px]">
                  <Menu className="h-5 w-5" />
                </Button>
              </SheetTrigger>
              <SheetContent side="left" className="bg-sidebar flex h-full w-64 flex-col items-stretch justify-between">
                <SheetTitle className="sr-only">Navigation Menu</SheetTitle>
                <SheetHeader className="flex justify-start text-left">
                  <AppLogoIcon className="h-6 w-6 fill-current text-black dark:text-white" />
                </SheetHeader>
                <div className="flex h-full flex-1 flex-col space-y-4 p-4">
                  <div className="flex h-full flex-col justify-between text-sm">
                    <div className="flex flex-col space-y-4">
                      <ProjectSwitch>
                        <Button variant="outline" className="flex w-full items-center justify-between px-1.5!">
                          <div className="flex items-center justify-center gap-2">
                            <Avatar className="size-6 rounded-md">
                              <AvatarFallback className="rounded-xs">
                                {useInitials()(page.props.project_provider.current?.name.replaceAll(' ', '') ?? 'Select project')}
                              </AvatarFallback>
                            </Avatar>
                            <span>{page.props.project_provider.current?.name || 'Select project'}</span>
                          </div>
                          <ChevronsUpDownIcon size={5} />
                        </Button>
                      </ProjectSwitch>

                      {mainNavItems.map((item) => (
                        <>
                          {item.redirect ? (
                            <a href={item.href} target={item.external ? '_blank' : '_self'} className="flex items-center space-x-2 font-medium">
                              {item.icon && <Icon iconNode={item.icon} className="h-5 w-5" />}
                              <span>{item.title}</span>
                            </a>
                          ) : (
                            <Link key={item.title} href={item.href} className="flex items-center space-x-2 font-medium">
                              {item.icon && <Icon iconNode={item.icon} className="h-5 w-5" />}
                              <span>{item.title}</span>
                            </Link>
                          )}
                        </>
                      ))}
                    </div>

                    <div className="flex flex-col space-y-4">
                      {rightNavItems.map((item) => (
                        <a
                          key={item.title}
                          href={item.href}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="flex items-center space-x-2 font-medium"
                        >
                          {item.icon && <Icon iconNode={item.icon} className="h-5 w-5" />}
                          <span>{item.title}</span>
                        </a>
                      ))}
                    </div>
                  </div>
                </div>
              </SheetContent>
            </Sheet>
          </div>

          <Link href={route('dashboard')} prefetch className="flex items-center space-x-2">
            <AppLogo />
          </Link>

          {/* Desktop Navigation */}
          <div className="ml-6 hidden h-full items-center space-x-6 lg:flex">
            <NavigationMenu className="flex h-full items-stretch">
              <NavigationMenuList className="flex h-full items-stretch space-x-2">
                <ProjectSwitch>
                  <NavigationMenuItem asChild>
                    <Button variant="outline" className="px-1.5!">
                      <div className="flex items-center justify-center gap-2">
                        {page.props.project_provider.current && (
                          <Avatar className="size-6 rounded-md">
                            <AvatarFallback className="rounded-xs">
                              {getInitials(page.props.project_provider.current.name.replaceAll(' ', '') ?? 'Select Project')}
                            </AvatarFallback>
                          </Avatar>
                        )}
                        <span>{page.props.project_provider.current?.name || 'Select project'}</span>
                      </div>
                      <ChevronsUpDownIcon size={5} />
                    </Button>
                  </NavigationMenuItem>
                </ProjectSwitch>
                {mainNavItems.map((item, index) => (
                  <NavigationMenuItem key={index} className="relative flex h-full items-center">
                    {item.redirect ? (
                      <a
                        href={item.href}
                        target={item.external ? '_blank' : '_self'}
                        className={cn(
                          navigationMenuTriggerStyle(),
                          window.location.href.startsWith(item.href) && activeItemStyles,
                          'h-9 cursor-pointer px-3',
                        )}
                      >
                        {item.icon && <Icon iconNode={item.icon} className="mr-2 h-4 w-4" />}
                        {item.title}
                      </a>
                    ) : (
                      <Link
                        href={item.href}
                        className={cn(
                          navigationMenuTriggerStyle(),
                          window.location.href.startsWith(item.href) && activeItemStyles,
                          'h-9 cursor-pointer px-3',
                        )}
                      >
                        {item.icon && <Icon iconNode={item.icon} className="mr-2 h-4 w-4" />}
                        {item.title}
                      </Link>
                    )}
                    {window.location.href.startsWith(item.href) && (
                      <div className="absolute bottom-0 left-0 h-0.5 w-full translate-y-px bg-black dark:bg-white"></div>
                    )}
                  </NavigationMenuItem>
                ))}
              </NavigationMenuList>
            </NavigationMenu>
          </div>

          <div className="ml-auto flex items-center space-x-2">
            <div className="relative flex items-center gap-2">
              <Refresh />
              <div className="hidden gap-2 lg:flex">
                {rightNavItems.map((item) => (
                  <TooltipProvider key={item.title} delayDuration={0}>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <a
                          href={item.href}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="group text-accent-foreground hover:bg-accent hover:text-accent-foreground focus-visible:border-ring focus-visible:ring-ring/50 inline-flex h-9 w-9 items-center justify-center rounded-md bg-transparent p-0 text-sm font-medium transition-colors outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50"
                        >
                          <span className="sr-only">{item.title}</span>
                          {item.icon && <Icon iconNode={item.icon} className="size-5 opacity-80 group-hover:opacity-100" />}
                        </a>
                      </TooltipTrigger>
                      <TooltipContent>
                        <p>{item.title}</p>
                      </TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                ))}
              </div>
            </div>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="size-10 rounded-md p-1">
                  <Avatar className="size-8 overflow-hidden rounded-md">
                    <AvatarImage src={auth.user.avatar} alt={auth.user.name} />
                    <AvatarFallback className="rounded-md border">{getInitials(auth.user.name)}</AvatarFallback>
                  </Avatar>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-56" align="end">
                <UserMenuContent user={auth.user} />
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </div>
      {breadcrumbs.length > 1 && (
        <div className="border-sidebar-border/70 flex w-full border-b">
          <div className="mx-auto flex h-12 w-full items-center justify-start px-4 text-neutral-500 md:max-w-7xl">
            <Breadcrumbs breadcrumbs={breadcrumbs} />
          </div>
        </div>
      )}
    </>
  );
}
