// resources/js/pages/auth/verify-email.tsx
import { Head, useForm, usePage } from '@inertiajs/react';
import { LoaderCircleIcon } from 'lucide-react';
import { FormEvent } from 'react';
import TextLink from '@/components/text-link';
import { Button } from '@/components/ui/button';
import AuthLayout from '@/layouts/auth-layout';
import { SharedData } from '@/types';
import { Alert, AlertDescription } from '@/components/ui/alert';

export default function VerifyEmail() {
  const page = usePage<SharedData>();
  const form = useForm({});

  const submit = (e: FormEvent) => {
    e.preventDefault();

    form.post(route('verification.send'));
  };

  return (
    <AuthLayout title="Verify email" description="Please verify your email address by clicking on the link we just emailed to you.">
      <Head title="Email verification" />

      {page.props.flash?.status === 'verification-link-sent' && (
        <Alert>
          <AlertDescription>
            <p>A new verification link has been sent to the email address you provided during registration.</p>
          </AlertDescription>
        </Alert>
      )}

      <form onSubmit={submit} className="space-y-6 text-center">
        <Button disabled={form.processing} variant="secondary">
          {form.processing && <LoaderCircleIcon className="animate-spin" />}
          Resend verification email
        </Button>

        <TextLink href={route('logout')} method="post" className="mx-auto block text-sm">
          Log out
        </TextLink>
      </form>
    </AuthLayout>
  );
}

// vue/src/pages/auth/verify-email.vue
<script setup lang="ts">
import TextLink from "@/components/text-link.vue";
import { Button } from "@/components/ui/button";
import AuthLayout from "@/layouts/auth-layout.vue";
import { Head, useForm } from "@inertiajs/vue3";
import { LoaderCircle } from "lucide-vue-next";

defineProps<{
  status?: string;
}>();

const form = useForm({});

const submit = () => {
  form.post(route("verification.send"));
};
</script>

<template>
  <AuthLayout
    title="Verify email"
    description="Please verify your email address by clicking on the link we just emailed to you."
  >
    <Head title="Email verification" />

    <div
      v-if="status === 'verification-link-sent'"
      class="mb-4 text-center text-sm font-medium text-green-600"
    >
      A new verification link has been sent to the email address you provided
      during registration.
    </div>

    <form @submit.prevent="submit" class="space-y-6 text-center">
      <Button :disabled="form.processing" variant="secondary">
        <LoaderCircle v-if="form.processing" class="h-4 w-4 animate-spin" />
        Resend verification email
      </Button>

      <TextLink
        :href="route('logout')"
        method="post"
        as="button"
        class="mx-auto block text-sm"
      >
        Log out
      </TextLink>
    </form>
  </AuthLayout>
</template>
