// resources/js/layouts/app-layout.tsx
import AppLayoutTemplate from '@/layouts/app/app-sidebar-layout';
import { type BreadcrumbItem } from '@/types';
import { type ReactNode } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import Toast from '@/components/toast';

interface AppLayoutProps {
  children: ReactNode;
  breadcrumbs?: BreadcrumbItem[];
}

export default function AppLayout({ children, breadcrumbs, ...props }: AppLayoutProps) {
  const queryClient = new QueryClient();

  return (
    <QueryClientProvider client={queryClient}>
      <AppLayoutTemplate breadcrumbs={breadcrumbs} {...props}>
        {children}
        <Toast />
      </AppLayoutTemplate>
    </QueryClientProvider>
  );
}

// vue/src/layouts/app-layout.vue
<script setup lang="ts">
import AppLayout from "@/layouts/app/app-header-layout.vue";
import type { BreadcrumbItem } from "@/types";
import Toast from '@/components/toast.vue';

interface Props {
  breadcrumbs?: BreadcrumbItem[];
}

withDefaults(defineProps<Props>(), {
  breadcrumbs: () => [],
});
</script>

<template>
  <AppLayout :breadcrumbs="breadcrumbs">
    <slot />
    <Toast />
  </AppLayout>
</template>
