// vue/src/components/project-switch.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { useForm, usePage } from '@inertiajs/vue3';
import ProjectForm from '@/pages/projects/components/project-form.vue';
import { PlusIcon } from 'lucide-vue-next';
import { SharedData } from '@/types';
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

const page = usePage<SharedData>();
const form = useForm({});
const projects = computed(() => page.props.project_provider.list || []);
const currentProjectId = ref(page.props.project_provider.current?.id?.toString() || '');

function handleProjectChange(projectId: string) {
  const selectedProject = projects.value.find((p) => p.id.toString() === projectId);
  if (selectedProject) {
    currentProjectId.value = selectedProject.id.toString();
    form.put(`/projects/${projectId}/switch?currentPath=${window.location.pathname}`);
  }
}
</script>

<template>
  <div class="flex items-center">
    <DropdownMenu :modal="false">
      <DropdownMenuTrigger as-child>
        <slot />
      </DropdownMenuTrigger>

      <DropdownMenuContent class="w-56" align="start">
        <DropdownMenuCheckboxItem
          v-for="project in projects"
          :key="project.id.toString()"
          :checked="currentProjectId === project.id.toString()"
          @update:checked="() => handleProjectChange(project.id.toString())"
        >
          {{ project.name }}
        </DropdownMenuCheckboxItem>

        <DropdownMenuSeparator />

        <ProjectForm>
          <DropdownMenuItem class="gap-0" as-child @select.prevent>
            <div class="flex items-center">
              <PlusIcon :size="16" />
              <span class="ml-2">Create new project</span>
            </div>
          </DropdownMenuItem>
        </ProjectForm>
      </DropdownMenuContent>
    </DropdownMenu>
  </div>
</template>

// stacks/react/src/components/project-switch.tsx
import { type SharedData } from '@/types';
import { useForm, usePage } from '@inertiajs/react';
import { ReactNode, useState } from 'react';
import {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { PlusIcon } from 'lucide-react';
import ProjectForm from '@/pages/projects/components/project-form';

export function ProjectSwitch({ children }: { children: ReactNode }) {
  const page = usePage<SharedData>();
  const [selectedProject, setSelectedProject] = useState(page.props.project_provider.current?.id.toString());
  const form = useForm();

  const handleProjectChange = (projectId: string) => {
    const selectedProject = page.props.project_provider.list?.find((project) => project.id.toString() === projectId);
    if (selectedProject) {
      setSelectedProject(selectedProject.id.toString());
      form.put(`/settings/projects/${projectId}/switch?currentPath=${encodeURIComponent(window.location.pathname)}`);
    }
  };

  return (
    <div className="flex items-center">
      <DropdownMenu modal={false}>
        <DropdownMenuTrigger asChild>{children}</DropdownMenuTrigger>
        <DropdownMenuContent className="w-56" align="start">
          {page.props.project_provider.list?.map((project) => (
            <DropdownMenuCheckboxItem
              key={project.id.toString()}
              checked={selectedProject === project.id.toString()}
              onCheckedChange={() => handleProjectChange(project.id.toString())}
            >
              {project.name}
            </DropdownMenuCheckboxItem>
          ))}
          <DropdownMenuSeparator />
          <ProjectForm>
            <DropdownMenuItem className="gap-0" asChild onSelect={(e) => e.preventDefault()}>
              <div className="flex items-center">
                <PlusIcon size={5} />
                <span className="ml-2">Create new project</span>
              </div>
            </DropdownMenuItem>
          </ProjectForm>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}
