// resources/js/pages/tokens/index.tsx
import SettingsLayout from '@/layouts/settings/layout';
import { Head, usePage } from '@inertiajs/react';
import Container from '@/components/container';
import Heading from '@/components/heading';
import { Button } from '@/components/ui/button';
import { DataTable } from '@/components/data-table';
import React from 'react';
import { Token } from '@/types/token';
import { columns } from '@/pages/tokens/components/columns';
import CreateToken from '@/pages/tokens/components/create-token';
import { BreadcrumbItem, PaginatedData } from '@/types';
import { PlusIcon } from 'lucide-react';

const breadcrumbs: BreadcrumbItem[] = [
  {
    title: 'Settings',
    href: '/settings',
  },
  {
    title: 'API Tokens',
    href: route('tokens.index'),
  },
];

export default function Tokens() {
  const page = usePage<{
    tokens: PaginatedData<Token>;
  }>();
  return (
    <SettingsLayout breadcrumbs={breadcrumbs}>
      <Head title="API Tokens" />
      <Container className="max-w-5xl">
        <div className="flex items-start justify-between">
          <Heading title="API Tokens" description="Here you can manage API tokens" />
          <div className="flex items-center gap-2">
            <CreateToken>
              <Button>
                <PlusIcon />
                Create token
              </Button>
            </CreateToken>
          </div>
        </div>
        <DataTable columns={columns} paginatedData={page.props.tokens} />
      </Container>
    </SettingsLayout>
  );
}

// vue/src/pages/tokens/index.vue
<script setup lang="ts">
import Layout from '@/layouts/settings/layout.vue';
import { BreadcrumbItem, PaginatedData } from '@/types';
import { Head, usePage } from '@inertiajs/vue3';
import { Token } from '@/types/token';
import Container from '@/components/container.vue';
import Heading from '@/components/heading.vue';
import DataTable from '@/components/data-table.vue';
import { columns } from '@/pages/tokens/components/columns';

const breadcrumbs: BreadcrumbItem[] = [
  {
    title: 'Settings',
    href: '/settings',
  },
  {
    title: 'Tokens',
    href: '/setting/tokens',
  },
];

const page = usePage<{
  tokens: PaginatedData<Token>;
}>();
</script>

<template>
  <Layout :breadcrumbs="breadcrumbs">
    <Head title="API Tokens" />
    <Container class="max-w-5xl">
      <div class="flex items-start justify-between">
        <Heading title="API Tokens" description="Here you can manage API tokens" />
        <div class="flex items-center gap-2">
          <!--            <CreateToken>-->
          <!--              <Button>-->
          <!--                <PlusIcon />-->
          <!--                Create token-->
          <!--              </Button>-->
          <!--            </CreateToken>-->
        </div>
      </div>
      <DataTable :columns="columns" :paginatedData="page.props.tokens" />
    </Container>
  </Layout>
</template>
