// react/src/pages/profile/components/two-factor.tsx
import { useForm, usePage } from '@inertiajs/react';
import type { SharedData } from '@/types';
import { FormEvent, ReactNode, useState } from 'react';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { CheckCircle2Icon, LoaderCircleIcon, XCircleIcon } from 'lucide-react';
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import InputError from '@/components/ui/input-error';
import axios from 'axios';

function Enable({ show = true }: { show?: boolean }): ReactNode {
  const page = usePage<
    SharedData & {
      two_factor_must_confirm: boolean;
    }
  >();
  const enableForm = useForm();
  const confirmForm = useForm({
    code: '',
  });
  const [open, setOpen] = useState(false);
  const [qrCode, setQrCode] = useState<string>('');
  const [qrCodeUrl, setQrCodeUrl] = useState<string>('');

  const submit = (e: FormEvent) => {
    e.preventDefault();
    enableForm.post(route('two-factor.enable'), {
      onSuccess: () => {
        axios.get(route('two-factor.qr-code')).then((response) => {
          setQrCode(response.data.svg);
          setQrCodeUrl(response.data.url);
        });
        setOpen(true);
      },
      preserveScroll: true,
      preserveState: true,
    });
  };

  const confirm = (e: FormEvent) => {
    e.preventDefault();
    confirmForm.post(route('two-factor.confirm'), {
      onSuccess: () => setOpen(false),
      preserveScroll: true,
      errorBag: 'confirmTwoFactorAuthentication',
    });
  };

  return (
    <>
      {show && (
        <Button onClick={submit} disabled={enableForm.processing}>
          {enableForm.processing && <LoaderCircleIcon className="animate-spin" />}
          Enable Two Factor
        </Button>
      )}
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Enable Two Factor</DialogTitle>
            <DialogDescription>Enabling two factor authentication</DialogDescription>
          </DialogHeader>
          <form id="confirm-form" onSubmit={confirm}>
            <div className="grid gap-6">
              <div className="grid gap-2">
                <Label htmlFor="qr-code">Scan this QR code with your authenticator app</Label>
                <div className="my-3 flex max-h-[400px] items-center justify-center">
                  <div dangerouslySetInnerHTML={{ __html: qrCode }}></div>
                </div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="qr-code-url">QR Code URL</Label>
                <Input id="qr-code-url" value={qrCodeUrl} disabled />
              </div>
              {page.props.two_factor_must_confirm && (
                <div className="grid gap-2">
                  <Label htmlFor="code">Confirmation Code</Label>
                  <Input
                    id="code"
                    type="text"
                    name="code"
                    placeholder="Enter the confirmation code"
                    autoFocus
                    value={confirmForm.data.code}
                    onChange={(e) => confirmForm.setData('code', e.target.value)}
                  />
                  <InputError message={confirmForm.errors.code} />
                </div>
              )}
            </div>
          </form>
          <DialogFooter>
            <DialogClose asChild>
              <Button variant="outline">Close</Button>
            </DialogClose>
            {page.props.two_factor_must_confirm && (
              <Button form="confirm-form" disabled={confirmForm.processing}>
                {confirmForm.processing && <LoaderCircleIcon className="animate-spin" />}
                Confirm
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

function Disable(): ReactNode {
  const [open, setOpen] = useState(false);
  const form = useForm();

  const submit = () => {
    form.delete(route('two-factor.disable'), {
      preserveScroll: true,
      onSuccess: () => setOpen(false),
    });
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="destructive">Disable Two Factor</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Disable two factor</DialogTitle>
          <DialogDescription>Disable two factor</DialogDescription>
        </DialogHeader>
        <p>Are you sure you want to enable two factor authentication?</p>
        <DialogFooter>
          <DialogClose asChild>
            <Button variant="outline">Cancel</Button>
          </DialogClose>
          <Button onClick={submit} variant="destructive" disabled={form.processing}>
            {form.processing && <LoaderCircleIcon className="animate-spin" />}
            Disable
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function Regenerate(): ReactNode {
  const [open, setOpen] = useState(false);
  const form = useForm();

  const submit = () => {
    form.post(route('two-factor.recovery-codes'), {
      preserveScroll: true,
      onSuccess: () => setOpen(false),
    });
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>Regenerate recovery codes</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Regenerate recovery codes</DialogTitle>
          <DialogDescription>Regenerate recovery codes</DialogDescription>
        </DialogHeader>
        <p>Are you sure you want to regenerate the recovery codes?</p>
        <DialogFooter>
          <DialogClose asChild>
            <Button variant="outline">Cancel</Button>
          </DialogClose>
          <Button onClick={submit} disabled={form.processing}>
            {form.processing && <LoaderCircleIcon className="animate-spin" />}
            Regenerate
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

export default function TwoFactor() {
  const page = usePage<
    SharedData & {
      two_factor_enabled: boolean;
      two_factor_recovery_codes: string[];
      two_factor_confirmed_at: string;
      two_factor_must_confirm: boolean;
    }
  >();

  const isEnabled = (): boolean => {
    if (page.props.two_factor_must_confirm) {
      return page.props.two_factor_enabled && page.props.two_factor_confirmed_at != null;
    }

    return page.props.two_factor_enabled;
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Two factor authentication</CardTitle>
        <CardDescription>Enable or Disable two factor authentication</CardDescription>
      </CardHeader>
      <CardContent>
        {isEnabled() ? (
          <>
            <Alert>
              <AlertDescription>
                <div className="flex items-center gap-2">
                  <CheckCircle2Icon className="text-success size-4" />
                  <p>Two factor authentication is enabled</p>
                </div>
              </AlertDescription>
            </Alert>
            {page.props.two_factor_recovery_codes.length > 0 && (
              <div className="grid gap-6">
                <div className="grid gap-2">
                  <Label htmlFor="recovery-codes">Recovery Codes</Label>
                  <Textarea id="recovery-codes" value={page.props.two_factor_recovery_codes?.join('\n') || ''} disabled rows={5} />
                </div>
              </div>
            )}
          </>
        ) : (
          <Alert>
            <AlertDescription>
              <div className="flex items-center gap-2">
                <XCircleIcon className="text-danger size-4" />
                Two factor authentication is <strong>not</strong> enabled
              </div>
            </AlertDescription>
          </Alert>
        )}
      </CardContent>
      <CardFooter className="gap-2">
        <Enable show={!isEnabled()} />
        {isEnabled() && (
          <>
            <Regenerate />
            <Disable />
          </>
        )}
      </CardFooter>
    </Card>
  );
}

// vue/src/pages/profile/components/two-factor.vue
<script lang="ts" setup>
import { ref, computed } from 'vue';
import { useForm, usePage } from '@inertiajs/vue3';
import axios from 'axios';
import { CheckCircle2Icon, LoaderCircleIcon, XCircleIcon } from 'lucide-vue-next';
import InputError from '@/components/input-error.vue';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';

const page = usePage<{
  two_factor_enabled: boolean;
  two_factor_recovery_codes: string[];
  two_factor_confirmed_at: string | null;
  two_factor_must_confirm: boolean;
}>();

const isEnabled = computed(() => {
  if (page.props.two_factor_must_confirm) {
    return page.props.two_factor_enabled && page.props.two_factor_confirmed_at !== null;
  }
  return page.props.two_factor_enabled;
});

const enableOpen = ref(false);
const enableForm = useForm({});
const confirmForm = useForm({ code: '' });
const qrCode = ref('');
const qrCodeUrl = ref('');

function enableSubmit() {
  enableForm.post(route('two-factor.enable'), {
    preserveScroll: true,
    preserveState: true,
    onSuccess: () => {
      axios.get(route('two-factor.qr-code')).then((response) => {
        qrCode.value = response.data.svg;
        qrCodeUrl.value = response.data.url;
      });
      enableOpen.value = true;
    },
  });
}

function confirmSubmit() {
  confirmForm.post(route('two-factor.confirm'), {
    preserveScroll: true,
    errorBag: 'confirmTwoFactorAuthentication',
    onSuccess: () => (enableOpen.value = false),
  });
}

const disableOpen = ref(false);
const disableForm = useForm({});
function disableSubmit() {
  disableForm.delete(route('two-factor.disable'), {
    preserveScroll: true,
    onSuccess: () => (disableOpen.value = false),
  });
}

const regenOpen = ref(false);
const regenForm = useForm({});
function regenSubmit() {
  regenForm.post(route('two-factor.recovery-codes'), {
    preserveScroll: true,
    onSuccess: () => (regenOpen.value = false),
  });
}

const twoFactorRecoveryCodes = computed(() => {
  return page.props.two_factor_recovery_codes.length ? page.props.two_factor_recovery_codes.join('\n') : '';
});
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Two factor authentication</CardTitle>
      <CardDescription>Enable or Disable two factor authentication</CardDescription>
    </CardHeader>
    <CardContent>
      <Alert v-if="isEnabled">
        <AlertDescription>
          <div class="flex items-center gap-2">
            <CheckCircle2Icon class="text-success size-4" />
            <p>Two factor authentication is enabled</p>
          </div>
        </AlertDescription>
      </Alert>
      <Alert v-else>
        <AlertDescription>
          <div class="flex items-center gap-2">
            <XCircleIcon class="text-danger size-4" />
            Two factor authentication is <strong>not</strong> enabled
          </div>
        </AlertDescription>
      </Alert>

      <div v-if="isEnabled && page.props.two_factor_recovery_codes.length" class="mt-6 grid gap-6">
        <div class="grid gap-2">
          <Label for="recovery-codes">Recovery Codes</Label>
          <Textarea id="recovery-codes" v-model="twoFactorRecoveryCodes" disabled rows="5" />
        </div>
      </div>
    </CardContent>
    <CardFooter class="gap-2">
      <Button v-if="!isEnabled" @click="enableSubmit" :disabled="enableForm.processing">
        <LoaderCircleIcon v-if="enableForm.processing" class="animate-spin" />
        Enable Two Factor
      </Button>

      <Dialog v-model:open="enableOpen">
        <DialogContent class="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Enable Two Factor</DialogTitle>
            <DialogDescription>Enabling two factor authentication</DialogDescription>
          </DialogHeader>
          <form id="confirm-form" @submit.prevent="confirmSubmit">
            <div class="grid gap-6">
              <div class="grid gap-2">
                <Label for="qr-code">Scan this QR code with your authenticator app</Label>
                <div class="my-3 flex max-h-[400px] items-center justify-center">
                  <div v-html="qrCode"></div>
                </div>
              </div>
              <div class="grid gap-2">
                <Label for="qr-code-url">QR Code URL</Label>
                <Input id="qr-code-url" :value="qrCodeUrl" disabled />
              </div>
              <div v-if="page.props.two_factor_must_confirm" class="grid gap-2">
                <Label for="code">Confirmation Code</Label>
                <Input id="code" type="text" name="code" placeholder="Enter the confirmation code" autofocus v-model="confirmForm.code" />
                <InputError :message="confirmForm.errors.code" />
              </div>
            </div>
          </form>
          <DialogFooter>
            <DialogClose asChild>
              <Button variant="outline">Close</Button>
            </DialogClose>
            <Button v-if="page.props.two_factor_must_confirm" form="confirm-form" :disabled="confirmForm.processing">
              <LoaderCircleIcon v-if="confirmForm.processing" class="animate-spin" />
              Confirm
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog v-model:open="regenOpen" v-if="isEnabled">
        <DialogTrigger asChild>
          <Button>Regenerate recovery codes</Button>
        </DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Regenerate recovery codes</DialogTitle>
            <DialogDescription>Regenerate recovery codes</DialogDescription>
          </DialogHeader>
          <p>Are you sure you want to regenerate the recovery codes?</p>
          <DialogFooter>
            <DialogClose asChild>
              <Button variant="outline">Cancel</Button>
            </DialogClose>
            <Button @click="regenSubmit" :disabled="regenForm.processing">
              <LoaderCircleIcon v-if="regenForm.processing" class="animate-spin" />
              Regenerate
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog v-model:open="disableOpen" v-if="isEnabled">
        <DialogTrigger asChild>
          <Button variant="destructive">Disable Two Factor</Button>
        </DialogTrigger>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Disable two factor</DialogTitle>
            <DialogDescription>Disable two factor</DialogDescription>
          </DialogHeader>
          <p>Are you sure you want to disable two factor authentication?</p>
          <DialogFooter>
            <DialogClose asChild>
              <Button variant="outline">Cancel</Button>
            </DialogClose>
            <Button @click="disableSubmit" variant="destructive" :disabled="disableForm.processing">
              <LoaderCircleIcon v-if="disableForm.processing" class="animate-spin" />
              Disable
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </CardFooter>
  </Card>
</template>
