// vue/src/layouts/settings/Layout.vue
<script setup lang="ts">
import Heading from '@/components/heading.vue';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { type NavItem } from '@/types';
import { Link, usePage } from '@inertiajs/vue3';
import AppLayout from '@/layouts/app-layout.vue';
import type { BreadcrumbItem } from '@/types';
import Container from '@/components/container.vue';
import { cn } from '@/lib/utils';
import { BriefcaseIcon, CommandIcon, UserIcon } from 'lucide-vue-next';

const sidebarNavItems: NavItem[] = [
  {
    title: 'Profile',
    href: '/settings/profile',
    icon: UserIcon,
  },
  // <php-saas:projects>
  {
    title: 'Projects',
    href: '/settings/projects',
    icon: BriefcaseIcon,
  },
  // </php-saas:projects>
  // <php-saas:tokens>
  {
    title: 'API Tokens',
    href: '/settings/tokens',
    icon: CommandIcon,
  },
  // </php-saas:tokens>
];

interface Props {
  breadcrumbs?: BreadcrumbItem[];
}

withDefaults(defineProps<Props>(), {
  breadcrumbs: () => [],
});

const currentUrl = window.location.pathname;
</script>

<template>
  <AppLayout :breadcrumbs="$props.breadcrumbs">
    <Container class="flex max-w-5xl flex-col items-start p-4 lg:flex-row lg:gap-5">
      <div class="space-y-5 lg:w-48">
        <nav class="flex flex-row gap-2 lg:flex-col">
          <Link
            v-for="item in sidebarNavItems"
            :key="item.title"
            :href="item.href"
            :class="
              cn(
                'hover:bg-muted flex items-center gap-2 rounded-md px-2 py-1.5 text-sm font-medium',
                item.onlyActivePath ? currentUrl === item.href : currentUrl.startsWith(item.href) ? 'bg-muted' : '',
              )
            "
          >
            <component :is="item.icon" class="h-4 w-4" />
            {{ item.title }}
          </Link>
        </nav>
      </div>
      <div class="w-full flex-1">
        <slot />
      </div>
    </Container>
  </AppLayout>
</template>

// react/src/layouts/settings/layout.tsx
import { cn } from '@/lib/utils';
import { type BreadcrumbItem, type NavItem } from '@/types';
import { Link } from '@inertiajs/react';
import { type ReactNode } from 'react';
import { BriefcaseIcon, CommandIcon, UserIcon } from 'lucide-react';
import AppLayout from '@/layouts/app-layout';
import Container from '@/components/container';

const sidebarNavItems: NavItem[] = [
  {
    title: 'Profile',
    href: '/settings/profile',
    icon: UserIcon,
  },
  // <php-saas:projects>
  {
    title: 'Projects',
    href: '/settings/projects',
    icon: BriefcaseIcon,
  },
  // </php-saas:projects>
  // <php-saas:tokens>
  {
    title: 'API Tokens',
    href: '/settings/tokens',
    icon: CommandIcon,
  },
  // </php-saas:tokens>
];

export default function SettingsLayout({ children, breadcrumbs }: { children: ReactNode; breadcrumbs?: BreadcrumbItem[] }) {
  if (typeof window === 'undefined') {
    return null;
  }

  return (
    <AppLayout breadcrumbs={breadcrumbs}>
      <Container className="flex max-w-5xl flex-col items-start p-4 lg:flex-row lg:gap-5">
        <div className="space-y-5 lg:w-48">
          <nav className="flex flex-row gap-2 lg:flex-col">
            {sidebarNavItems.map((item) => (
              <Link
                key={item.title}
                href={item.href}
                className={cn(
                  'hover:bg-muted flex items-center gap-2 rounded-md px-2 py-1.5 text-sm font-medium',
                  item.onlyActivePath ? window.location.pathname === item.href : window.location.pathname.startsWith(item.href) ? 'bg-muted' : '',
                )}
              >
                {item.icon && <item.icon className="size-4" />}
                {item.title}
              </Link>
            ))}
          </nav>
        </div>
        <div className="w-full flex-1">{children}</div>
      </Container>
    </AppLayout>
  );
}
