// vue/src/pages/projects/components/project-form.vue
<script setup lang="ts">
import { ref, watch, defineProps, defineEmits } from 'vue';
import { useForm } from '@inertiajs/vue3';
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import InputError from '@/components/input-error.vue';
import { Label } from '@/components/ui/label';
import { LoaderCircle } from 'lucide-vue-next';
import type { Project } from '@/types/project';

const props = defineProps<{
  project?: Project;
  defaultOpen?: boolean;
}>();

const emit = defineEmits<{
  (e: 'update:open', value: boolean): void;
}>();

const open = ref(props.defaultOpen ?? false);

watch(() => props.defaultOpen, (val) => {
  if (val !== undefined) open.value = val;
});

function handleOpenChange(value: boolean) {
  open.value = value;
  emit('update:open', value);
}

const form = useForm({
  name: props.project?.name ?? '',
});

function submit(e?: Event) {
  if (e) e.preventDefault();

  if (props.project) {
    form.put(route('projects.update', props.project.id), {
      onSuccess: () => (open.value = false),
    });
  } else {
    form.post(route('projects.store'), {
      onSuccess: () => (open.value = false),
    });
  }
}
</script>

<template>
  <Dialog :open="open" @update:open="handleOpenChange">
    <DialogTrigger as-child>
      <slot />
    </DialogTrigger>

    <DialogContent class="sm:max-w-md">
      <DialogHeader>
        <DialogTitle>{{ props.project ? 'Edit Project' : 'Create Project' }}</DialogTitle>
        <DialogDescription>
          {{ props.project ? 'Edit the project details.' : 'Here you can create a new project.' }}
        </DialogDescription>
      </DialogHeader>

      <form id="project-form" @submit="submit">
        <div class="grid gap-6">
          <div class="grid gap-2">
            <Label for="name">Name</Label>
            <Input
              id="name"
              type="text"
              v-model="form.data.name"
              name="name"
            />
            <InputError :message="form.errors.name" />
          </div>
        </div>
      </form>

      <DialogFooter>
        <DialogClose as-child>
          <Button type="button" variant="outline">Cancel</Button>
        </DialogClose>
        <Button
          form="project-form"
          type="button"
          :disabled="form.processing"
          @click="submit"
        >
          <LoaderCircle v-if="form.processing" class="animate-spin mr-2" />
          Save
        </Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// resources/js/pages/projects/components/project-form.tsx
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { FormEvent, ReactNode, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { LoaderCircle } from 'lucide-react';
import { useForm } from '@inertiajs/react';
import { Form, FormField, FormFields } from '@/components/ui/form';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import InputError from '@/components/ui/input-error';
import { Project } from '@/types/project';

export default function ProjectForm({
  project,
  defaultOpen,
  onOpenChange,
  children,
}: {
  project?: Project;
  defaultOpen?: boolean;
  onOpenChange?: (open: boolean) => void;
  children: ReactNode;
}) {
  const [open, setOpen] = useState(defaultOpen || false);
  useEffect(() => {
    if (defaultOpen) {
      setOpen(defaultOpen);
    }
  }, [setOpen, defaultOpen]);

  const handleOpenChange = (open: boolean) => {
    setOpen(open);
    if (onOpenChange) {
      onOpenChange(open);
    }
  };

  const form = useForm({
    name: project?.name || '',
  });

  const submit = (e: FormEvent) => {
    e.preventDefault();

    if (project) {
      form.put(route('projects.update', project.id), {
        onSuccess() {
          setOpen(false);
        },
      });
      return;
    }

    form.post(route('projects.store'), {
      onSuccess() {
        setOpen(false);
      },
    });
  };

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>{children}</DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>{project ? 'Edit Project' : 'Create Project'}</DialogTitle>
          <DialogDescription className="sr-only">{project ? 'Edit the project details.' : 'Create a new project.'}</DialogDescription>
        </DialogHeader>
        <Form id="project-form" onSubmit={submit} className="p-4">
          <FormFields>
            <FormField>
              <Label htmlFor="name">Name</Label>
              <Input type="text" id="name" name="name" value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} />
              <InputError message={form.errors.name} />
            </FormField>
          </FormFields>
        </Form>
        <DialogFooter>
          <DialogClose asChild>
            <Button type="button" variant="outline">
              Cancel
            </Button>
          </DialogClose>
          <Button form="project-form" type="button" onClick={submit} disabled={form.processing}>
            {form.processing && <LoaderCircle className="animate-spin" />}
            Save
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
