// vue/src/pages/auth/confirm-password.vue
<script setup lang="ts">
import InputError from "@/components/input-error.vue";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import AuthLayout from "@/layouts/auth-layout.vue";
import { Head, useForm } from "@inertiajs/vue3";
import { LoaderCircle } from "lucide-vue-next";

const form = useForm({
  password: "",
});

const submit = () => {
  form.post(route("password.confirm"), {
    onFinish: () => {
      form.reset();
    },
  });
};
</script>

<template>
  <AuthLayout
    title="Confirm your password"
    description="This is a secure area of the application. Please confirm your password before continuing."
  >
    <Head title="Confirm password" />

    <form @submit.prevent="submit">
      <div class="space-y-6">
        <div class="grid gap-2">
          <Label htmlFor="password">Password</Label>
          <Input
            id="password"
            type="password"
            class="mt-1 block w-full"
            v-model="form.password"
            required
            autocomplete="current-password"
            autofocus
          />

          <InputError :message="form.errors.password" />
        </div>

        <div class="flex items-center">
          <Button class="w-full" :disabled="form.processing">
            <LoaderCircle v-if="form.processing" class="h-4 w-4 animate-spin" />
            Confirm Password
          </Button>
        </div>
      </div>
    </form>
  </AuthLayout>
</template>

// resources/js/pages/auth/confirm-password.tsx
import { Head, useForm } from '@inertiajs/react';
import { LoaderCircleIcon } from 'lucide-react';
import { FormEvent } from 'react';
import InputError from '@/components/ui/input-error';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import AuthLayout from '@/layouts/auth';
import { Form, FormField, FormFields } from '@/components/ui/form';

export default function ConfirmPassword() {
  const form = useForm<{ password: string }>({
    password: '',
  });

  const submit = (e: FormEvent) => {
    e.preventDefault();

    form.post(route('password.confirm.store'), {
      onFinish: () => form.reset('password'),
    });
  };

  return (
    <AuthLayout title="Confirm your password" description="This is a secure area of the application. Please confirm your password before continuing.">
      <Head title="Confirm password" />

      <Form onSubmit={submit}>
        <FormFields>
          <FormField>
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              name="password"
              placeholder="Password"
              autoComplete="current-password"
              value={form.data.password}
              autoFocus
              onChange={(e) => form.setData('password', e.target.value)}
            />
            <InputError message={form.errors.password} />
          </FormField>

          <div className="flex items-center">
            <Button className="w-full" disabled={form.processing}>
              {form.processing && <LoaderCircleIcon className="animate-spin" />}
              Confirm password
            </Button>
          </div>
        </FormFields>
      </Form>
    </AuthLayout>
  );
}
